# Numpy Arrays

In [1]:
#Import numpy libary
import numpy as np

In [2]:
x=np.array([45,67,57,98])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 98]
<class 'numpy.ndarray'>
int32


In [3]:
x=np.array([45,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [4]:
x=np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [7]:
x1=np.array([[20,60], [30,40]])
print(x1)
print(type(x1))
print(x1.shape)
print(x1.dtype)

[[20 60]
 [30 40]]
<class 'numpy.ndarray'>
(2, 2)
int32


In [8]:
#Reshaping an array
a=np.array([10,20,30,40])
b=a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [19]:
a=np.array([10,20,30,40,50,60,70,80,90])
b=a.reshape(3,3)
print(b)
print(b.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


In [17]:
c=np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [21]:
#use of around()
d=np.array([1.3467, 3.10987, 4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [22]:
d=np.array([1.3467, 3.10987, 4.91236])
print(d)
print(np.around(np.sqrt(d), 2))

[1.3467  3.10987 4.91236]
[1.16 1.76 2.22]


# 2D Array

In [24]:
a1=np.array([[1,2,3,4], [5,6,7, np.NAN]])
print(a1)
print(a1.shape)
print(a1.dtype)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7. nan]]
(2, 4)
float64


In [25]:
a1.reshape(4, 2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7., nan]])

In [26]:
#Use of astype( to covert the data type)
a1_copy=a1.astype(str)
print(a1_copy)
a1_copy.dtype

[['1.0' '2.0' '3.0' '4.0']
 ['5.0' '6.0' '7.0' 'nan']]


dtype('<U32')

In [27]:
a2=np.array([[3,4,6], [7,9,10], [4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [28]:
print(a2.sum(axis=1))
print(a2.sum(axis=0))

[13 26 22]
[14 19 28]


In [30]:
print(a2)
print(a2.mean(axis=0))
print(a2.mean(axis=1))

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.66666667 6.33333333 9.33333333]
[4.33333333 8.66666667 7.33333333]


In [31]:
#Matrix operations
a3=np.array([[3,4,5], [7,2,8], [9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [32]:
a3=np.array([[3,4,5], [7,2,8], [9,1,6]])
print(a3)
np.fill_diagonal(a3, 0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [34]:
A=np.array([[1,2], [3,4]])
B=np.array([[5,6], [7,8]])

#preform matrix multiplication
C=np.matmul(A, B)
print(c)

[3 4 5 6 7 8 9]


In [35]:
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [36]:
#Accessing the array elements
a4=np.array([[3,4,5], [7,2,8], [9,1,6], [10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [40]:
a4[1][1]

2

In [41]:
a4[3][2]

18

In [42]:
a4[1:3, 0:2]

array([[7, 2],
       [9, 1]])